version: '3.1'

services:
  notes-service:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "notes-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=notes
    volumes:
      - pgdata:/var/lib/postgresql/data