version: '2.4'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  mydb:  #same as --name
    image: postgres:10
    environment: 
      POSTGRES_PASSWORD: example
      # or - 'POSTGRES_PASSWORD=example'
    volumes: 
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      - 'dbnetwork'
    labels:
      version: '10'
      creation-date: today
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      # source of good labels http://label-schema.org/rc1/
    #command: if you want to change default command
  website:
    image: sample-application
    build: #default values
      context: .
      dockerfile: Dockerfile 
      args:
        version: '5'
    ports:
      - '8080:8080'
    networks:
      - dbnetwork
    links:
      - 'mydb:database'
    depends_on:
      mydb:
        condition: service_healthy
    
volumes:
  dbdata:

networks:
  dbnetwork:
