version: '3.1'

#Write rest of the compose file.
#You have to build an image with application, connect it to db and publish port 8080

services:
  notes-service:
    depends_on:
      - db
  db:

volumes: